name: Update Node.js Versions

on:
  schedule:
    - cron: '18 23 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Fetch Node.js Versions
        run: |
          # 公式JSONを一度取得
          curl -s https://nodejs.org/dist/index.json > node_data.json

          # LTSとCurrentを抽出
          LATEST_LTS=$(cat node_data.json | jq -r '[.[] | select(.lts != false)][0].version')
          LATEST_CURRENT=$(cat node_data.json | jq -r '.[0].version')

          # フォルダを作成して保存
          mkdir -p nodejs
          echo "$LATEST_LTS" > nodejs/lts.txt
          echo "$LATEST_CURRENT" > nodejs/current.txt

      - name: Commit and Push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # 変更があるか確認
          git add nodejs/*.txt
          if ! git diff --staged --quiet; then
            git commit -m "Update Node.js versions: $(cat nodejs/lts.txt) / $(cat nodejs/current.txt)"
            # 履歴を整理して最新の状態に合わせる
            git pull --rebase origin main
            git push origin main
          else
            echo "No changes to commit"
          fi
